# Generated by Django 4.1 on 2022-08-22 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=160, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre cliente')),
                ('apellido_cliente', models.CharField(max_length=150, verbose_name='Apellido cliente')),
                ('dpi', models.CharField(max_length=15, verbose_name='Documento Personal de Identificacion')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='fecha nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion domiciliar')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=160, verbose_name='Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto%Y/%m/%d')),
                ('precio_prducto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('categoria_prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.categoria')),
            ],
            options={
                'verbose_name': 'Prodcuto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('detalle_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.producto')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.venta')),
            ],
            options={
                'verbose_name': 'Prodcuto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
